
'use client'
import Head from "next/head";
import { Col, Row } from "reactstrap";
import ProjectTables from "@/app/components/dashboard/ProjectTable";
import '../styles/style.scss';

export default function Home() {
  return (
    <div className="container-fluid">
      <Head>
        <title>Xtreme Starter Next Js App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="px-4 py-5">
        {/***Sales & Feed***/}
        <Row>
          <Col sm="12" lg="6" xl="7" xxl="8">
            {/* <SalesChart /> */}
          </Col>
          <Col sm="12" lg="6" xl="5" xxl="4">
            {/* <Feeds /> */}
          </Col>
        </Row>
        {/***Table ***/}

        <Row>
          <Col lg="12" sm="12">
            <ProjectTables />
          </Col>
        </Row>
        {/***Blog Cards***/}
      </div>
    </div>
  );
}