
'use client'
import Head from "next/head";
import { Col, Row } from "reactstrap";
import SalesChart from "@/app/components/dashboard/SalesChart";
import Feeds from "@/app/components/dashboard/Feeds";
import ProjectTables from "@/app/components/dashboard/ProjectTable";
import TopCards from "@/app/components/dashboard/TopCards";
import Blog from "@/app/components/dashboard/Blog";
import '../styles/style.scss';

export default function Home() {
  return (
    <div className="container-fluid">
      <Head>
        <title>Xtreme Starter Next Js App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="px-4 py-5">
        {/* <Row>
          <Col sm="6" lg="3">
            <TopCards
              bg="bg-light-success text-success"
              title="Profit"
              subtitle="Yearly Earning"
              earning="$21k"
              icon="bi bi-wallet"
            />
          </Col>
          <Col sm="6" lg="3">
            <TopCards
              bg="bg-light-danger text-danger"
              title="Refunds"
              subtitle="Refund given"
              earning="$1k"
              icon="bi bi-coin"
            />
          </Col>
          <Col sm="6" lg="3">
            <TopCards
              bg="bg-light-warning text-warning"
              title="New Project"
              subtitle="Yearly Project"
              earning="456"
              icon="bi bi-basket3"
            />
          </Col>
          <Col sm="6" lg="3">
            <TopCards
              bg="bg-light-info text-into"
              title="Sales"
              subtitle="Weekly Sales"
              earning="210"
              icon="bi bi-bag"
            />
          </Col>
        </Row> */}
        {/***Sales & Feed***/}
        <Row>
          <Col sm="12" lg="6" xl="7" xxl="8">
            {/* <SalesChart /> */}
          </Col>
          <Col sm="12" lg="6" xl="5" xxl="4">
            {/* <Feeds /> */}
          </Col>
        </Row>
        {/***Table ***/}

        <Row>
          <Col lg="12" sm="12">
            <ProjectTables />
          </Col>
        </Row>
        {/***Blog Cards***/}
      </div>
    </div>
  );
}